python3 src/run_uie_lora.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path Salesforce/codet5-large \
   --model_revision 4ca0fb4dc19d81c35a7dffe4356d8a6236a687b4 \
   --data_dir CL_Benchmark \
   --task CodeTrans \
   --output_dir logs_and_outputs/cl4code/outputs/1-CodeTrans \
   --per_device_train_batch_size 1 \
   --per_device_eval_batch_size 1 \
   --gradient_accumulation_steps 1 \
   --learning_rate 1e-04 \
   --num_train_epochs 2 \
   --run_name olora_run1 \
   --add_task_name False \
   --add_dataset_name False \
   --generation_max_length 256 \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --evaluation_strategy epoch \
   --save_strategy no \
   --lamda_1 0.5 \
   --lamda_2 0 \
   --max_train_samples 2 \
   --max_eval_samples 2 \
   --max_predict_samples 2 \
   --local_rank -1 
